from tkinter import *
root = Tk()
root.title("Registration Form")
root.geometry("400x400")
Label(root, text="Name").grid(row=0, column=0)
name = Entry(root)
name.grid(row=0, column=1)
Label(root, text="Email").grid(row=1, column=0)
email = Entry(root)
email.grid(row=1, column=1)
Label(root, text="Password").grid(row=2, column=0)
password = Entry(root, show="*")
password.grid(row=2, column=1)
Label(root, text="Gender").grid(row=3, column=0)
gender = StringVar()
Radiobutton(root, text="Male", variable=gender, value="Male").grid(row=3, column=1)
Radiobutton(root, text="Female", variable=gender, value="Female").grid(row=3, column=2)
Label(root, text="Hobbies").grid(row=4, column=0)
h1 = IntVar()
h2 = IntVar()
Checkbutton(root, text="Reading", variable=h1).grid(row=4, column=1)
Checkbutton(root, text="Sports", variable=h2).grid(row=4, column=2)
def submit():
    print("Name:", name.get())
    print("Email:", email.get())
    print("Gender:", gender.get())
Button(root, text="Submit", command=submit).grid(row=5, column=1)
root.mainloop()
